// public class exception2{
//     public static void main(String[] args) {
//         int[] arr={2,1,2,34};
//         try {
//             System.out.println(arr[6]);
            
//         } catch (Exception e) {
//             System.out.println(e);
//         }
//         System.out.println("hello");
//     }
// }


// public class exception2{
//     public static void main(String[] args) {
//         String str= null ;
//         System.out.println(str.toUpperCase());
//         try {
            
//         } catch (Exception e) {
//             System.out.println(e);
        
//         }
//     }
// }




public class exception2{
    public static void main(String[] args) {
        int[]arr= {1,2,3};
        try {
            System.out.println(arr[5]);
        } catch (Exception e) {
            System.out.println("Exception occurred:" +e);
        }
        System.out.println("End of program");
    }
}


